### ISSUE TITLE
TOC runs off the page for long documents

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs-bootstrap#3]
Originally reported against MkDocs. https://github.com/mkdocs/mkdocs/issues/204

**Comment by Mailaender** [comment]
This seems to be a regression, because `mkdocs==0.17.3` example: https://docs.openra.net/en/release/traits/ will show scrollbars.

**Comment by Mailaender** [comment]
```css
.bs-sidebar {
    max-height: 640px; max-width: 240px; overflow: auto;
}

.nav-link {
    overflow-wrap: anywhere;
}
```

is my extra CSS solution which adds the scrollbar back in and avoids long class names overflowing: https://docs.openra.net/en/bleed/traits/
