### ISSUE TITLE
TOC text is invisible unless hovered on

### ISSUE THREAD

**Issue by martin-martin** [mkdocs/mkdocs-bootstrap#33]
I tested the theme with a minimal setup, here's my `mkdocs.yaml` file:

```yaml
site_name: Test
site_description: Test Bootstrap Theme
site_author: Anonymous
theme:
  name: bootstrap
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
```

The resulting navigation of the theme is hard to use because the text is blue on blue:

![bootstrap](https://user-images.githubusercontent.com/12371494/97070785-5f8c8d80-15db-11eb-9d6c-ded5b9d09834.gif)

Any ideas why that might be happening? Thanks!
